-- compile packages for debug
ALTER session set current_schema = "ODMRSYS";
/

ALTER PACKAGE ODMR_CONSTANT
   COMPILE DEBUG PACKAGE; 

ALTER PACKAGE ODMR_UTIL
   COMPILE DEBUG PACKAGE; 

ALTER PACKAGE ODMR_ENGINE
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE
   COMPILE DEBUG BODY;    

ALTER PACKAGE ODMR_ENGINE_DATA
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_DATA
   COMPILE DEBUG BODY;       

ALTER PACKAGE ODMR_ENGINE_DATA_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_DATA_SEC
   COMPILE DEBUG BODY;       

ALTER PACKAGE ODMR_ENGINE_MINING
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_MINING
   COMPILE DEBUG BODY;       
   
ALTER PACKAGE ODMR_ENGINE_MINING_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_MINING_SEC
   COMPILE DEBUG BODY;        
   
ALTER PACKAGE ODMR_ENGINE_OUTPUT
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_OUTPUT
   COMPILE DEBUG BODY;        
   
ALTER PACKAGE ODMR_ENGINE_OUTPUT_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_OUTPUT_SEC
   COMPILE DEBUG BODY;    
   
ALTER PACKAGE ODMR_ENGINE_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_SEC
   COMPILE DEBUG BODY;      
   
ALTER PACKAGE ODMR_ENGINE_TRANSFORMS
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_TRANSFORMS
   COMPILE DEBUG BODY;     

ALTER PACKAGE ODMR_ENGINE_TRANSFORMS_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_TRANSFORMS_SEC
   COMPILE DEBUG BODY;     

ALTER PACKAGE ODMR_ENGINE_TEXT_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_TEXT_SEC
   COMPILE DEBUG BODY;     

ALTER PACKAGE ODMR_ENGINE_TEXT
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_ENGINE_TEXT
   COMPILE DEBUG BODY;

ALTER PACKAGE ODMR_INTERNAL_UTIL
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_INTERNAL_UTIL
   COMPILE DEBUG BODY;  

ALTER PACKAGE ODMR_INTERNAL_UTIL_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_INTERNAL_UTIL_SEC
   COMPILE DEBUG BODY;  

ALTER PACKAGE ODMR_MSG
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_MSG
   COMPILE DEBUG BODY;  

ALTER PACKAGE ODMR_PROJECT
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_PROJECT
   COMPILE DEBUG BODY;  

ALTER PACKAGE ODMR_PROJECT_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_PROJECT_SEC
   COMPILE DEBUG BODY;  

ALTER PACKAGE ODMR_WORKFLOW
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_WORKFLOW
   COMPILE DEBUG BODY;  

ALTER PACKAGE ODMR_WORKFLOW_SEC
   COMPILE DEBUG PACKAGE; 
 
ALTER PACKAGE ODMR_WORKFLOW_SEC
   COMPILE DEBUG BODY;  

grant debug any procedure to ODMRSYS;
grant debug connect session to ODMRSYS;
grant debug any procedure to DMUSER;
grant debug connect session to DMUSER;

   