-- Usage @dropusergrants.sql <P1>
--    P1: User account will have all grants associated with ODMr revoked
-- Example: @dropusergrants.sql DMUSER

DEFINE USER_ACCOUNT = &&1

revoke ODMRUSER from "&USER_ACCOUNT";

REVOKE EXECUTE ON ODMR_ENGINE_TEXT from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.START_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.CLEANUP_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.SUBFLOW_START_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.SUBFLOW_CLEANUP_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.DATASOURCE_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.DATAPROFILE_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.CLASS_BUILD_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.REGRESS_BUILD_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.CLUST_BUILD_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.ASSOC_BUILD_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.ANOMALY_BUILD_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.MODEL_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.TEST_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.APPLY_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.MODELDETAILS_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.CREATETABLE_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.UPDATETABLE_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.TRANSFORMATIONS_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.JOIN_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.AGGREGATION_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.COLUMNFILTER_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.FILTERDETAILS_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.SAMPLE_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.ROWFILTER_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.FEATURE_BUILD_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.TEXT_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.BUILDTEXT_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.APPLYTEXT_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON ODMRSYS.BUILDTEXT_REF_PROG from "&USER_ACCOUNT";
/
REVOKE EXECUTE ON CTX_DDL from "&USER_ACCOUNT";  
/