-- Usage @usergrants.sql <P1>
--    P1: User account being configured for use with ODMR
-- Example: @usergrants.sql DMUSER

DEFINE USER_ACCOUNT = &&1

grant ODMRUSER to "&USER_ACCOUNT";

--Text APIs require direct grant of ODMR_ENGINE_TEXT to user account, not role
GRANT EXECUTE ON ODMR_ENGINE_TEXT TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.START_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.CLEANUP_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.SUBFLOW_START_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.SUBFLOW_CLEANUP_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.DATASOURCE_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.DATAPROFILE_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.CLASS_BUILD_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.REGRESS_BUILD_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.CLUST_BUILD_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.ASSOC_BUILD_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.ANOMALY_BUILD_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.MODEL_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.TEST_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.APPLY_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.MODELDETAILS_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.CREATETABLE_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.UPDATETABLE_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.TRANSFORMATIONS_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.JOIN_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.AGGREGATION_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.COLUMNFILTER_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.FILTERDETAILS_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.SAMPLE_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.ROWFILTER_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.FEATURE_BUILD_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.TEXT_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.BUILDTEXT_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.APPLYTEXT_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON ODMRSYS.BUILDTEXT_REF_PROG TO "&USER_ACCOUNT";
/
GRANT EXECUTE ON CTX_DDL to "&USER_ACCOUNT";  -- for ODMr Classic compatibility
/
@@alterUserDefaultRole.sql &USER_ACCOUNT